---
title: COGS 137 Course Schedule
execute: 
  freeze: false
---

Here you'll find topics, links to materials, and deadlines for the entire term. Should any dates changes, this page will be updated throughout the quarter.

```{r}
#| echo: false
#| message: false
#| warning: false

library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1_95DsxhANrTJGUMfZwGlFC3y_9rKuCQPWPRIUAFlOgo/edit?gid=0#gid=0")
```

```{r}
#| echo: false

d |>
  select(-dow) |>
  mutate(
    date = as.Date(date)
  ) |>
  gt() |>
  fmt_date(date, date_style = 31) |>
  sub_missing(columns = c(week, topic, prepare, materials, due), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week)
    ) |>
  cols_align(
    align = "right", 
    columns = c(date)
    ) |>
  cols_align(
    align = "left", 
    columns = c(topic, prepare, materials, due)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, prepare, materials)
    )
  ) |>
  fmt_markdown(
    columns = c(topic, prepare, materials, due)
  ) |>
  cols_width(
    week ~ px(45),
    date ~ px(100), 
    topic ~ px(300),
    prepare ~ px(250),
    materials ~ px(90),
    due ~ px(185)
  ) |>
  cols_label_with(fn = function(x) {
      janitor::make_clean_names(x, case = "title") |>
        toupper() |>
        stringr::str_replace_all("^|$", "**") |>
        md()
    }) |>
  tab_options(table.font.size = 13) |>
  opt_row_striping()
```
