{
  "hash": "11a61ac2f08e829291ac55e32d2aa218",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"COGS 137 - Midterm (Fa23)\"\noutput: \n  html: \n    embed-resources: true\n    highlight: pygments\n    css: lab.css\n    preview-links: auto\n    execute:\n      eval: false\n---\n\n\n## Packages\n\nYou will need the `tidyverse` and `tidymodels` packages for this midterm. If working on datahub, these packages have been installed, but you will need to load them. You are allowed, but not required, to use additional packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n\nrichmondway <- read_csv(\"data/richmondway.csv\")\n```\n:::\n\n\n## The data\n\nThe data we'll be using come from The [Richmondway R Pacakge](https://github.com/deepshamenghani/richmondway) and have been provided by the [TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-09-26) team.\n\nThe data are stored in `data/richmondway.csv` You'll want to read each table in and understand what each variable represents prior to completing the exam.\n\nEach variable and the data overall are described in detail [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-09-26/readme.md#data-dictionary). You should click on that link to see what information is stored in each column in the datasets. But briefly, this dataset includes data from three seasons of the TV show Ted Lasso. Each observation is a single episode of the show. The variables, generally, relate to the number of times Roy Kent (a foul-mouthed character on the show) and the entire cast say the F-word (often referred to as dropping the **\"F bomb\"**).\n\n## Questions\n\n### Question 1 (0.5 points)\n\nF-bomb summary:\n\n1)  Calculate how many times total Roy Kent said the F-word within each season.\n2)  Comment on in which season Roy Kent said the F-word the most overall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrichmondway |>\n  group_by(Season) |>\n  summarize(count = sum(F_count_RK))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Season count\n   <dbl> <dbl>\n1      1    56\n2      2   106\n3      3   138\n```\n\n\n:::\n:::\n\n\n1)  Season 1: 56; Season 2: 106; Season 3: 138\n2)  Season 3\n\n### Question 2 (0.5 points)\n\nDetermine how many episodes had more F bombs by Roy Kent than every other character on the show combined (*excluding Roy Kent*)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# utilizing F_perc column\nrichmondway |> filter(F_perc > 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 16\n  Character Episode_order Season Episode Season_Episode F_count_RK F_count_total\n  <chr>             <dbl>  <dbl>   <dbl> <chr>               <dbl>         <dbl>\n1 Roy Kent              3      1       3 S1_e3                   7            13\n2 Roy Kent              9      1       9 S1_e9                  14            22\n3 Roy Kent             11      2       1 S2_e1                  11            16\n4 Roy Kent             15      2       5 S2_e5                  23            32\n5 Roy Kent             16      2       6 S2_e6                  12            18\n6 Roy Kent             22      2      12 S2_e12                 23            44\n7 Roy Kent             24      3       2 S3_e2                  16            31\n8 Roy Kent             28      3       6 S3_e6                  13            21\n9 Roy Kent             32      3      10 S3_e10                 10            18\n# ℹ 9 more variables: cum_rk_season <dbl>, cum_total_season <dbl>,\n#   cum_rk_overall <dbl>, cum_total_overall <dbl>, F_score <dbl>, F_perc <dbl>,\n#   Dating_flag <chr>, Coaching_flag <chr>, Imdb_rating <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# OR \n\n# calculating diff if you didn't see/underestand F_perc column\nrichmondway |> \n  mutate(not_roy = F_count_total - F_count_RK) |>\n  filter(F_count_RK > not_roy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 17\n  Character Episode_order Season Episode Season_Episode F_count_RK F_count_total\n  <chr>             <dbl>  <dbl>   <dbl> <chr>               <dbl>         <dbl>\n1 Roy Kent              3      1       3 S1_e3                   7            13\n2 Roy Kent              9      1       9 S1_e9                  14            22\n3 Roy Kent             11      2       1 S2_e1                  11            16\n4 Roy Kent             15      2       5 S2_e5                  23            32\n5 Roy Kent             16      2       6 S2_e6                  12            18\n6 Roy Kent             22      2      12 S2_e12                 23            44\n7 Roy Kent             24      3       2 S3_e2                  16            31\n8 Roy Kent             28      3       6 S3_e6                  13            21\n9 Roy Kent             32      3      10 S3_e10                 10            18\n# ℹ 10 more variables: cum_rk_season <dbl>, cum_total_season <dbl>,\n#   cum_rk_overall <dbl>, cum_total_overall <dbl>, F_score <dbl>, F_perc <dbl>,\n#   Dating_flag <chr>, Coaching_flag <chr>, Imdb_rating <dbl>, not_roy <dbl>\n```\n\n\n:::\n:::\n\n\nThere were nine episodes where Roy Kent had more F bombs than all of the other characters combined.\n\n### Question 3 (1.5 points)\n\nGenerate an exploratory\\* visualization that displays the typical range of Roy Kent F-bombs in an episode, broken down by season and explain three things you've learned about the data from this plot.\n\n::: aside\n\\*Note: exploratory here means that it does NOT have to be polished. Do NOT worry about title, axis labels, etc. We just care about understanding the data here. (If you do customize, you will NOT be penalized. It's just not required for this question.)\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(richmondway, aes(x=factor(Season), y=F_count_RK)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](midterm-fa23-ans_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nHere we see that the median value increases from season 1 to season 3, with a typical season 1 episode having approximately 6 F bombs from Roy Kent. (However, there was an outlier episode with almost 15 in Season 1). By season 3, the median value was more than 10. The episode with the most Roy Kent F bombs was season 2, with more than 25!\n\nRubric:\n\n- handles season as a factor \n- correct variables \n- boxplot (or other viz that displays range) \n- three things observed are accurate\n\n### Question 4 (1 point)\n\nGenerate an exploratory\\* visualization that displays the relationship between `Imdb_rating` and Roy Kent F-bombs. Describe the relationship you see in this plot.\n\n::: aside\n\\*Note: exploratory here means that it does NOT have to be polished. Do NOT worry about title, axis labels, etc. We just care about understanding the data here. (If you do customize, you will NOT be penalized. It's just not required for this question.)\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(richmondway, aes(x=Imdb_rating, y=F_count_RK)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](midterm-fa23-ans_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nRubric:\n\n- scatterplot most typical \n- correct variables plotted \n- interpretation correct (little to no relationship)\n\n### Question 5 (1 point)\n\nBackground: Keeley is a character on Ted Lasso who is dating Roy Kent for some but not all of the episodes.\n\nGenerate a visualization that enables you to answer the questions below: - Does the median number of Roy Kent F bombs differ when Roy is dating Keeley (vs. when he is not)? - In the episode when Roy Kent dropped the most F bombs, was Roy dating Keeley?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(richmondway, aes(x=Dating_flag, y=F_count_RK)) + \n  geom_boxplot()  +\n  geom_jitter(width=0.25)\n```\n\n::: {.cell-output-display}\n![](midterm-fa23-ans_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n-   boxplot most typical\n-   answers correct (fewer when dating Keeley; most when he is dating Keeley)\n\n### Question 6 (1.5 points)\n\nWhat is the effect of dating Keeley on the number of Roy Kent F bombs? Generate a linear model that answers this question. Interpret the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(F_count_RK ~ factor(Dating_flag) , data = richmondway) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term                   estimate std.error statistic     p.value\n  <chr>                     <dbl>     <dbl>     <dbl>       <dbl>\n1 (Intercept)              8.84        1.31    6.74   0.000000128\n2 factor(Dating_flag)Yes  -0.0421      1.97   -0.0213 0.983      \n```\n\n\n:::\n:::\n\n\nRubric: \n\n- outcome is F bombs \n- dating handled as a factor \n- interpretation is correct. (A typical episode when they're not dating has 8.84 F bombs. And, on average there are slightly fewer F bombs when Keeley and Roy are dating (-0.04); however, this effect is quite small (in magnitude and significance) ). Must interpret intercept and effect/slope.\n\n### Question 7 (1.5 points)\n\nBackground: In Season 1, Roy Kent is a player. After retiring, he eventually becomes a coach. So, Roy is a coach in some but not all of the episodes.\n\nWhat is the effect of whether or not Roy Kent is coaching on the number of Roy Kent F bombs? Generate a linear model that answers this question. Interpret the results. Then, comment on whether coaching or dating Keeley is a better predictor of Roy Kent F bombs and explain how you came to that conclusion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(F_count_RK ~ factor(Coaching_flag) , data = richmondway) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term                     estimate std.error statistic  p.value\n  <chr>                       <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                  5.79      1.36      4.26 0.000167\n2 factor(Coaching_flag)Yes     5.16      1.77      2.92 0.00639 \n```\n\n\n:::\n:::\n\n\nRubric: \n\n- model correct \n- interpretation is correct. (When not coaching, 5.79 F bombs; when coaching 5.16 more (on average)). Must interpret intercept and effect/slope. \n- comment states that coaching is better (likely uses R\\^2 and/or p-value; effect size not appropriate for model comparison)\n\n### Question 8 (2.5 points)\n\nGenerate a **polished** visualization that allows viewers to compare proportion/percentage of F-bombs broken down by season for Roy Kent vs those by everyone other than Roy Kent. Be sure to consider effective visualization principles discussed in class in this plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- richmondway |>\n  mutate(`All Other Characters` = F_count_total - F_count_RK,\n         `Roy Kent` = F_count_RK) |>\n  select(Season, `Roy Kent`, `All Other Characters` ) |>\n  pivot_longer(cols=-Season, names_to=\"character\")\n\nggplot(df, aes(x=value, y=str_wrap(character, width = 10), fill=factor(Season), group=character)) + \n  geom_col(position=\"fill\") +\n  scale_fill_manual(values = c(\"1\" = \"#deebf7\",\n                                \"2\" = \"#9ecae1\",\n                                \"3\" = \"#3182bd\")) +\n  labs(title=\"Third Season of Ted Lasso comprises almost half of the total F bombs\", \n       subtitle=\"Similar proportion of F bombs across seasons for Roy Kent vs. all other characters\",\n       x = \"Proportion of F Bombs\",\n       y = NULL,\n       fill = \"Season\") +\n  guides(color = \"none\") +\n  theme_classic(base_size = 14) + \n  theme(plot.title.position = \"plot\")\n```\n\n::: {.cell-output-display}\n![](midterm-fa23-ans_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nRubric: \n\n- determined/calculated number of not-roy \n- proportions displayed \n- title describes take-home \n- axes labeled correctly \n- good design principles (colors, labels, etc.)\n\n### Question 9 (3 points)\n\nRecreate the plot included below using the data you've been working with. Once you have created the visualization, describe at least one change that you would make to improve the design of the plot.\n\nNote: the hex values for the colors used in this plot are: \"#deebf7\" (lightest), \"#9ecae1\", and \"#3182bd\" (darkest)\n\n![](img/plot-to-recreate-fa23.png)\n\nCode to reproduce plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(richmondway, aes(x=Episode, y=F_count_total, group=Season, color=as.factor(Season))) + \n  geom_line(linewidth=2) +\n  geom_point(size=3) +\n  scale_x_continuous(n.breaks=12) +\n  scale_color_manual(values = c(\"1\" = \"#deebf7\",\n                                \"2\" = \"#9ecae1\",\n                                \"3\" = \"#3182bd\")) + \n  theme_classic() +\n  labs(title = \"Ted Lasso Episodes always have at least a handful of F bombs, but typically there are at least 20\",\n       subtitle = \"Number of F Bombs Dropped by all characters per episode across 3 seasons of Ted Lasso\",\n       y=\"F Count\",\n       color=\"Season\") +\n  theme(plot.title.position = \"plot\")\n```\n:::\n\n\n### Question 10 (1 point)\n\nDescribe at least 1) two things you like about how the plot in Question 9 communicates the data and 2) two things you would do differently to make this a more effective visualization for communication.\n\nLots of possible answers here. Most common cons: title too wordy!, line color, text size, would add grid lines, woudl visualize differently\n\n# Submit\n\n::: callout-important\nYou'll always want to knit your RMarkdown document to HTML and review that HTML document to ensure it includes all the information you want and looks as you intended, as we grade from the knit HTML.\n:::\n\n*Yay, you're done! To finish up and submit, first **knit** your file to HTML. Be sure to select both your .Rmd and .html documents when choosing what to commit! Then, commit all remaining changes and push. Before you wrap up the assignment, make sure all documents are updated on your GitHub repo.*\n",
    "supporting": [
      "midterm-fa23-ans_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}