{
  "hash": "c02a8c60e84670aa8397b0ca3e61cc94",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"COGS 137 - Winter 2023 - Practice Midterm (Answers)\"\noutput: \n  html: \n    highlight: pygments\n    css: lab.css\n    preview-links: auto\n    execute:\n      eval: false\n---\n\n\n## Rules\n\nThere will be rules spelled out on the real midterm. Be sure to read them before taking the real exam. There will also be an academic integrity statement for you to complete. Replace the `____________` with your name below on the real deal.\n\n## Academic Integrity Statement\n\nI, \\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_\\_, hereby state that I have not communicated with or gained information in any way from my classmates or anyone during this exam, and that all work is my own.\n\n**A note on sharing / reusing code:** We are well aware that a huge volume of code is available on the web to solve any number of problems. For this exam you are allowed to make use of any online resources (e.g. StackOverflow) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). You are also not allowed to ask a question on an external forum, you can only use answers to questions that have already been answered. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. All communication with classmates is explicitly forbidden.\n\n## Getting help\n\nBecause we cannot be available to all students across the entire length of the (real) exam, there will be no questions of instructional staff about the exam. If you find wording confusing or are unsure, note that in your answer and explain how you interpreted it. This will be taken into consideration during grading. If you are having technical difficulties or think there is an error on the exam, DM or email Prof Ellis immediately and she'll work with you as soon as possible.\n\n## Grading and feedback\n\nThe (real) exam is worth 16% of your grade. You will be graded on the correctness of your code, correctness of your answers (often there are multiple \"correct\" answers, by design), the clarity of your explanations, and the overall organization of your document. (There's no one \"right\" organization, but we should be able to easily navigate your midterm to find what we're looking for.)\n\n## Logistics\n\nAnswer the questions in the document called `practice-exam.Rmd`. Add your code and narrative in the spaces below each question. Add code chunks as needed. Use as many lines as you need, but keep your narrative concise. Be sure to knit your file to HTML and view the file prior to turning it in.\n\n## Packages\n\nYou will need the `tidyverse` package for this (practice) midterm. (For the real deal, you'll need `tidyverse` and `tidymodels`.) If working on datahub, this package has been installed, but you will need to load it. No other packages are required, but if for some reason you want to load in another package, you are permitted to do so.\n\n## The data\n\nThe dataset you'll be working with on this practice midterm is all about beach volleyball. The full dataset is explained in detail [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-19/readme.md) and includes match-level data from 76,756 volleyball matches. **You should click on that link to see what information is stored in each column in this dataset and what information is included in each column.**\n\nBriefly, what you'll use for this midterm is a subset of the full dataset, including only the 11,699 observations (rows) from 2018 and 2019 but all of the original columns. Each row summarizes the results from a *single, distinct match* played in a volleyball tournament.\n\nTo briefly describe beach volleyball, it is a sport played 2 on 2, so each match involves only 4 players. These data include matches from two different volleyball `circuit`s, the international FIVB and the US-centric AVP. You will not need to know much at all about this sport to complete this midterm, and anything you need to know will be explained.\n\nThe data are stored in `data/vb_matches.csv`. You'll need to read the dataset in prior to answering any questions on the midterm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.3     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\ndf <- read_csv('data/vb_matches.csv')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 11699 Columns: 65\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (17): circuit, tournament, country, gender, w_player1, w_p1_country, w_...\ndbl  (42): year, match_num, w_p1_age, w_p1_hgt, w_p2_age, w_p2_hgt, l_p1_age...\ndate  (5): date, w_p1_birthdate, w_p2_birthdate, l_p1_birthdate, l_p2_birthdate\ntime  (1): duration\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n## Questions\n\n**Question 1 (0.75 points)** - How many FIVB and AVP matches are included in this dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  group_by(circuit) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n# Groups:   circuit [2]\n  circuit     n\n  <chr>   <int>\n1 AVP      2656\n2 FIVB     9043\n```\n\n\n:::\n:::\n\n\n-   2656 AVP\n-   9043 FIVB\n\n**Question 2 (0.75 points)** - Find the match with the longest duration.\n    a.  Where was this tournament played (City & Country)?\n    b.  How long did the match last?\n    c.  Who were the two winners?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  slice(which.max(duration))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 65\n  circuit tournament country        year date       gender match_num w_player1  \n  <chr>   <chr>      <chr>         <dbl> <date>     <chr>      <dbl> <chr>      \n1 AVP     Austin     United States  2018 2018-05-17 M             37 Nathan Yang\n# ℹ 57 more variables: w_p1_birthdate <date>, w_p1_age <dbl>, w_p1_hgt <dbl>,\n#   w_p1_country <chr>, w_player2 <chr>, w_p2_birthdate <date>, w_p2_age <dbl>,\n#   w_p2_hgt <dbl>, w_p2_country <chr>, w_rank <chr>, l_player1 <chr>,\n#   l_p1_birthdate <date>, l_p1_age <dbl>, l_p1_hgt <dbl>, l_p1_country <chr>,\n#   l_player2 <chr>, l_p2_birthdate <date>, l_p2_age <dbl>, l_p2_hgt <dbl>,\n#   l_p2_country <chr>, l_rank <chr>, score <chr>, duration <time>,\n#   bracket <chr>, round <chr>, w_p1_tot_attacks <dbl>, w_p1_tot_kills <dbl>, …\n```\n\n\n:::\n:::\n\n\na)  Austin, USA\nb)  1h 42 min\nc)  Nathan Yang & Steven Irvin\n\n\n```{=html}\n<!-- -->\n```\n\n\n**Question 3 (1.5 points)** - Across all tournaments included in this dataset, which teams have won the most tournaments? Your response should include both the winning players, their gender, and the number of tournaments they've won in descending order. Who has the most wins? How many men's and how many women's teams are in the top 10?\n\nNote: \"winning a tournament\" is indicated by winning either a \"Gold Medal\" (FIVB) or \"Finals\" (AVP) match, specified in the `bracket` column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  filter(bracket %in% c(\"Gold Medal\", \"Finals\")) |> \n  group_by(w_player1, w_player2, gender) |>\n  count() |> \n  arrange(desc(n)) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n# Groups:   w_player1, w_player2, gender [10]\n   w_player1              w_player2                 gender     n\n   <chr>                  <chr>                     <chr>  <int>\n 1 Alix Klineman          \"April Ross\"              W         11\n 2 Anders Mol             \"Christian Sorum\"         M         10\n 3 Melissa Humana-Paredes \"Sarah Pavan\"             W          6\n 4 Nick Lucena            \"Phil Dalhausser\"         M          6\n 5 Jake Gibb              \"Taylor Crabb\"            M          5\n 6 Jingzhe Wang           \"Shuhui Wen\"              W          5\n 7 Agatha Bednarczuk      \"Eduarda \\\"Duda\\\" Lisboa\" W          4\n 8 Aleksandrs Samoilovs   \"Janis Smedins\"           M          4\n 9 Betsi Flint            \"Emily Day\"               W          4\n10 Alexander Brouwer      \"Robert Meeuwsen\"         M          3\n```\n\n\n:::\n:::\n\n\n-   Alix Klineman and April Ross have won the most tournaments\n-   There are 5 men's teams and 5 women's teams\n\n**Question 4 (1.5 points)** - Of *only* the AVP tournaments included in this dataset, how many *different* cities hosted tournaments in 2018 and 2019? And, which cities (if any) hosted a tournament in both 2018 and 2019?\n\nNote that `tournament`s are named for the city hosting the tournament.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# distinct locations\ndf |> \n  filter(circuit == 'AVP') |>\n  distinct(tournament)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 1\n  tournament      \n  <chr>           \n1 Austin          \n2 New York        \n3 Seattle         \n4 San Francisco   \n5 Hermosa Beach   \n6 Manhattan Beach \n7 Chicago         \n8 Waikiki         \n9 Huntington Beach\n```\n\n\n:::\n:::\n\n\n-   9 distinct locations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocations <- df |> \n  filter(circuit == 'AVP') |>\n  group_by(year, date) |> \n    distinct(tournament) \n\ndf |>\n  filter(circuit == \"AVP\") |>\n  group_by(year, date) |>\n  distinct(tournament) |>\n  group_by(tournament) |>\n  count() |>\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n# Groups:   tournament [6]\n  tournament          n\n  <chr>           <int>\n1 Austin              2\n2 Chicago             2\n3 Hermosa Beach       2\n4 Manhattan Beach     2\n5 New York            2\n6 Seattle             2\n```\n\n\n:::\n:::\n\n\n-   6 locations were duplicates between 2018 and 2019, including Chicago, Manhattan Beach, Hermosa Beach, Seattle, New York, and Austin\n\n**Question 5 (2.5 points)** - Prof Ellis plays a lot of women's beach volleyball and is only 5'5\" (65 inches). Despite not having the sheer talent or raw athletic ability to make it as a professional volleyball player, she wonders if she ever had a chance at her height. To help her out, answer each of the following:\n    a.  Who was the shortest women's player to compete in a tournament in 2018/2019?\n    b.  How tall are they?\n    c.  Did they *win* a tournament in 2018 or 2019?\n\nReminder: there are 4 players in each match whose height should be considered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find shortest in each column\ndf |>\n  filter(gender == \"W\") |>\n  summarize(min_p1 = min(w_p1_hgt, na.rm=TRUE), \n            min_p2  = min(w_p2_hgt, na.rm=TRUE), \n            min_l_p1 = min(l_p1_hgt, na.rm=TRUE),\n            min_l_p2 = min(l_p2_hgt, na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  min_p1 min_p2 min_l_p1 min_l_p2\n   <dbl>  <dbl>    <dbl>    <dbl>\n1     63     64       62       61\n```\n\n\n:::\n\n```{.r .cell-code}\n# determine the shortest player\ndf |> filter(l_p2_hgt == 61)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 65\n  circuit tournament    country  year date       gender match_num w_player1     \n  <chr>   <chr>         <chr>   <dbl> <date>     <chr>      <dbl> <chr>         \n1 FIVB    Visakhapatnam India    2019 2019-02-28 W              7 Melissa Fuchs…\n2 FIVB    Visakhapatnam India    2019 2019-02-28 W             16 Ekaterina Fil…\n# ℹ 57 more variables: w_p1_birthdate <date>, w_p1_age <dbl>, w_p1_hgt <dbl>,\n#   w_p1_country <chr>, w_player2 <chr>, w_p2_birthdate <date>, w_p2_age <dbl>,\n#   w_p2_hgt <dbl>, w_p2_country <chr>, w_rank <chr>, l_player1 <chr>,\n#   l_p1_birthdate <date>, l_p1_age <dbl>, l_p1_hgt <dbl>, l_p1_country <chr>,\n#   l_player2 <chr>, l_p2_birthdate <date>, l_p2_age <dbl>, l_p2_hgt <dbl>,\n#   l_p2_country <chr>, l_rank <chr>, score <chr>, duration <time>,\n#   bracket <chr>, round <chr>, w_p1_tot_attacks <dbl>, w_p1_tot_kills <dbl>, …\n```\n\n\n:::\n:::\n\n\nPerumal Yogeshwari was the shortest to compete (at 61 inches). By deduction, since this is the `l_p2` column, we know that she did not win any tournaments.\n\n**Question 6 (3 pts)** - Which country has hosted the most FIVB tournaments? Did this differ by year? Generate a visualization that shows how many *FIVB* tournaments each country hosted. Allow viewer to visualize this by year. And, be sure each tournament is only counted once (regardless of how many games were played).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  filter(circuit == 'FIVB') |>\n  distinct(tournament, year, .keep_all = TRUE) |>\n  ggplot(aes(y=fct_infreq(country))) + \n  geom_bar() + \n  facet_wrap(~year) +\n  labs(y=NULL,\n       x=\"Count\",\n       title = \"Number of FIVB tournaments hosted by each country\") + \n  theme_bw() +\n  theme(plot.title.position = \"plot\")\n```\n\n::: {.cell-output-display}\n![](practice-exam-fa21-ans_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Question 7 (3 pts)** - Recreate the plot included below using the data you've been working with. Once you have created the visualization, in no more than one paragraph, describe what you think the point of this visualization might be.\n\n*Hint:* The visualization uses the variable `avg_team_height`, which is not included in the provided data frame. You will have to create `avg_team_height` yourself, be determining the average (mean) team height for each winning team.\n\n![](img/plot_to_recreate.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  filter(circuit == 'AVP') |>\n  mutate(avg_team_height = (w_p1_hgt + w_p2_hgt)/2) |>\n  ggplot(aes(x = fct_infreq(w_p1_country), y = avg_team_height, fill=w_p1_country)) +\n  geom_boxplot() + \n  facet_wrap(~gender, \n             scales=\"free_y\", \n             nrow=2) +\n  labs(y = 'Average Team Height (in)',\n       x = 'Country',\n       title = 'Average team heights for AVP match winners in 2018 and 2019') +\n  theme(plot.title.position = \"plot\") +\n  guides(fill=\"none\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1288 rows containing non-finite values (`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](practice-exam-fa21-ans_files/figure-html/unnamed-chunk-9-1.png){width=100%}\n:::\n:::\n\n\nVisualizes which countries have the tallest winning teams on average. For men, we see that players from the Netherlands are quite tall. For Women, it's the US and Canada.\n\n8.  **Question 8 (1 pts)** - If you were in charge of designing the plot you just recreated in the plot above, what changes would you make to improve its effectiveness as a visualization? (You do not have to write any code for this question, just explain the different design/viz choices you would make.)\n\n-   swap axes\n-   accurate/more informative labelling labeling\n-   meaningful ordering of countries (geography?)\n-   improved color choices (flag colors?)\n-   increase text size\n-   remove background\n-   etc.\n\n<br>\n",
    "supporting": [
      "practice-exam-fa21-ans_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}