{
  "hash": "bda4c674368692d3816e09335f4f0971",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"09-mlr\"\nauthor: \"Professor Shannon Ellis\"\ndate: \"2023-10-31\"\n\nformat:\n  html: \n    output-file: 09-mlr.html\n    embed-resources: true\n  revealjs:\n    output-file: 09-mlr-slides.html\n    slide-number: true\n    chalkboard: false \n    preview-links: auto\n    logo: images/cogs137-logo-hex.png\n    css: slides.css\n    footer: <https://cogs137.github.io/website/>\n    scrollable: true\n    embed-resources: true\n    execute:\n      echo: true\n      eval: true\n---\n\n\n# Multiple Linear Regression {background-color=\"#92A86A\"}\n\n## Q&A {.smaller}\n\n> Q: What are some ways we can make our visuals accessible? For example, how can we account for color blind people when incorporating graphs and figures in our presentation?\\\n> A: Love this question! One way to do this is to use tools built for just this purpose! For example, for color blindness, [ColorBrewer2](https://colorbrewer2.org/) allows you to toggle for color palletes that are \"colorblind safe.\" Similarly, for written content online, ensuring that you're including alt-text for all images, to enable visual understanding by those with vision impariments/differences. For those with learning differences (i.e. dyslexia, ADHD), I'm *sure* there's research out there with respect to viz, and I should make myself more familiar, but ensuring that you're not using very similar acronyms/initialisms for different context or using consistent icons (Rather than letters) across visualizations, etc. can really help individuals with learning differences and overall make your viz more consistent/understandable. This is just the tip of the iceberg. Additional suggestions [here](https://www.highcharts.com/blog/tutorials/10-guidelines-for-dataviz-accessibility/).\n\n## Course Announcements\n\n-   👻 Happy Halloween!\n    -   No OH today after class\n    -   Make up: tomorrow 10-11AM (CSB 243)\n-   🔬 There is NO lab to turn in this week\n    -   Lab will be used for midterm review\n    -   Come to lab with questions!\n-   🏫 Midterm is due next Monday at 11:59PM\n    -   will be released 5PM Friday\n    -   completed individually\n    -   open notes/open Internet\n    -   NOT timed\n    -   typically takes students \\~2.5h to complete (big range: 2-15h)\n-   Lab05 & HW03 will be released next Monday\n\n\n::: {.cell}\n\n:::\n\n\n## Suggested Reading\n\nIntroduction to Modern Statistics Chapter 8: [Linear Regression with Multiple Predictors](https://openintro-ims.netlify.app/model-mlr.html)\n\n## Agenda\n\n-   Multiple Linear Regression\n    -   Multiple predictors\n    -   Main vs interaction effects\n    -   Model comparison\n    -   Backward selection\n\n## Packages & Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n\n. . .\n\n**Data: Paris Paintings**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp <- read_csv(\"https://raw.githubusercontent.com/COGS137/datasets/main/paris_paintings.csv\", \n               na = c(\"n/a\", \"\", \"NA\")) |> \n  mutate(log_price = log(price))\n```\n:::\n\n\n-   Number of observations: 3393\n-   Number of variables: 62\n\n# Two numerical predictors {background-color=\"#92A86A\"}\n\n## Multiple predictors\n\n-   Response variable: `log_price`\n-   Explanatory variables: Width and height\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_mod <- linear_reg() |>\n  set_engine(\"lm\")\n\npp_fit <- lin_mod |>\n  fit(log_price ~ Width_in + Height_in, data = pp)\ntidy(pp_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   4.77     0.0579      82.4  0       \n2 Width_in      0.0269   0.00373      7.22 6.58e-13\n3 Height_in    -0.0133   0.00395     -3.36 7.93e- 4\n```\n\n\n:::\n:::\n\n\n## Linear model with multiple predictors\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   4.77     0.0579      82.4  0       \n2 Width_in      0.0269   0.00373      7.22 6.58e-13\n3 Height_in    -0.0133   0.00395     -3.36 7.93e- 4\n```\n\n\n:::\n:::\n\n\n<br>\n\n$$\\widehat{log\\_price} = 4.77 + 0.0269 \\times width - 0.0133 \\times height$$\n\n. . .\n\n[❓ How do we interpret this model?]{style=\"background-color: #ADD8E6\"}\n\n# Numerical and categorical predictors {background-color=\"#92A86A\"}\n\n## Price, surface area, and living artist\n\n-   Explore the relationship between price of paintings and surface area, conditioned on whether or not the artist is still living\n-   First visualize and explore, then model\n\n. . .\n\n-   But first, prep the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp <- pp |>\n  mutate(artistliving = case_when(artistliving == 0 ~ \"Deceased\", \n                                  TRUE ~ \"Living\"))\n\npp |>\n  count(artistliving)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  artistliving     n\n  <chr>        <int>\n1 Deceased      2937\n2 Living         456\n```\n\n\n:::\n:::\n\n\n## Typical surface area\n\n::: panel-tabset\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/unnamed-chunk-4-1.png){width=100%}\n:::\n:::\n\n\nTypical surface area appears to be less than 1000 square inches (\\~ 80cm x 80cm). There are very few paintings that have surface area above 5000 square inches.\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp, aes(x = Surface, fill = artistliving)) +\n  geom_histogram(binwidth = 500) + \n  facet_grid(artistliving ~ .) +\n  scale_fill_manual(values = c(\"#E48957\", \"#071381\")) +\n  guides(fill = \"none\") +\n  labs(x = \"Surface area\", y = NULL) +\n  geom_vline(xintercept = 1000) +\n  geom_vline(xintercept = 5000, linetype = \"dashed\", color = \"gray\")\n```\n:::\n\n:::\n\n## Narrowing the scope\n\n::: panel-tabset\n### Plot\n\nFor simplicity let's focus on the paintings with `Surface < 5000`:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/unnamed-chunk-5-1.png){width=100%}\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_Surf_lt_5000 <- pp |>\n  filter(Surface < 5000)\n\nggplot(data = pp_Surf_lt_5000, \n       aes(y = log_price, x = Surface, color = artistliving, shape = artistliving)) +\n  geom_point(alpha = 0.5) +\n  labs(color = \"Artist\", shape = \"Artist\") +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\"))\n```\n:::\n\n:::\n\n## Facet to get a better look\n\n::: panel-tabset\n### Plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/unnamed-chunk-6-1.png){width=100%}\n:::\n:::\n\n\n### Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pp_Surf_lt_5000, \n       aes(y = log_price, x = Surface, color = artistliving, shape = artistliving)) +\n  geom_point(alpha = 0.5) +\n  facet_wrap(~artistliving) +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\")) +\n  labs(color = \"Artist\", shape = \"Artist\")\n```\n:::\n\n:::\n\n## Two ways to model\n\n-   **Main effects:** Assuming relationship between surface and logged price **does not vary** by whether or not the artist is living.\n-   **Interaction effects:** Assuming relationship between surface and logged price **varies** by whether or not the artist is living.\n\n## Interacting explanatory variables\n\n-   Including an interaction effect in the model allows for different slopes, i.e. nonparallel lines.\n-   This implies that the regression coefficient for an explanatory variable would change as another explanatory variable changes.\n-   This can be accomplished by adding an interaction variable: the product of two explanatory variables.\n\n## Two ways to model {.smaller}\n\n::: columns\n::: {.column width=\"30%\"}\n-   **Main effects:** Assuming relationship between surface and logged price **does not vary** by whether or not the artist is living\n-   **Interaction effects:** Assuming relationship between surface and logged price **varies** by whether or not the artist is living\n:::\n\n::: {.column width=\"70%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/pp-main-int-viz-1.png){width=800%}\n:::\n:::\n\n:::\n:::\n\n. . .\n\n[❓ Which does your intuition/knowledge of the data suggest is more appropriate?]{style=\"background-color: #ADD8E6\"}\n\nPut a <font color=\"#32cb31\">green</font> sticky if you think main; <font color=\"#ff65a3\">pink</font> if you think interaction.\n\n## Fit model with main effects {.smaller}\n\n-   Response variable: `log_price`\n-   Explanatory variables: `Surface` area and `artistliving`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_main_fit <- lin_mod |>\n  fit(log_price ~ Surface + artistliving, data = pp_Surf_lt_5000)\ntidy(pp_main_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term               estimate std.error statistic  p.value\n  <chr>                 <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        4.88     0.0424       115.   0       \n2 Surface            0.000265 0.0000415      6.39 1.85e-10\n3 artistlivingLiving 0.137    0.0970         1.41 1.57e- 1\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times artistliving$$\n\n## Solving the model\n\n-   Non-living artist: Plug in 0 for `artistliving`\n\n$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times 0$\\\n$= 4.88 + 0.000265 \\times surface$\n\n. . .\n\n-   Living artist: Plug in 1 for `artistliving`\n\n$\\widehat{log\\_price} = 4.88 + 0.000265 \\times surface + 0.137 \\times 1$\\\n$= 5.017 + 0.000265 \\times surface$\n\n## Visualizing main effects {.smaller}\n\n::: columns\n::: {.column width=\"40%\"}\n-   **Same slope:** Rate of change in price as the surface area increases does not vary between paintings by living and non-living artists.\n-   **Different intercept:** Paintings by living artists are consistently more expensive than paintings by non-living artists.\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/unnamed-chunk-7-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## Interpreting main effects {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(pp_main_fit) |> \n  mutate(exp_estimate = exp(estimate)) |>\n  select(term, estimate, exp_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  term               estimate exp_estimate\n  <chr>                 <dbl>        <dbl>\n1 (Intercept)        4.88           132.  \n2 Surface            0.000265         1.00\n3 artistlivingLiving 0.137            1.15\n```\n\n\n:::\n:::\n\n\n::: incremental\n-   All else held constant, for each additional square inch in painting's surface area, the price of the painting is predicted, on average, to be higher by a factor of 1.\n-   All else held constant, paintings by a living artist are predicted, on average, to be higher by a factor of 1.15 compared to paintings by an artist who is no longer alive.\n-   Paintings that are by an artist who is not alive and that have a surface area of 0 square inches are predicted, on average, to be 132 livres.\n:::\n\n## Main vs. interaction effects {.smaller}\n\n-   The way we specified our main effects model only lets `artistliving` affect the intercept.\n-   Model implicitly assumes that paintings with living and deceased artists have the *same slope* and only allows for *different intercepts*.\n\n. . .\n\n[❓ What seems more appropriate in this case?]{style=\"background-color: #ADD8E6\"}\n\n-   Same slope and same intercept for both colors\n-   Same slope and different intercept for both colors\n-   Different slope and different intercept for both colors\n\n## Interaction: `Surface * artistliving` {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/unnamed-chunk-8-1.png){width=80%}\n:::\n:::\n\n\n## Fit model with interaction effects {.smaller}\n\n-   Response variable: `log_price`\n-   Explanatory variables: `Surface` area, `artistliving`, and their interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_int_fit <- lin_mod |>\n  fit(log_price ~ Surface * artistliving, data = pp_Surf_lt_5000)\ntidy(pp_int_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                        estimate std.error statistic    p.value\n  <chr>                          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)                 4.91     0.0432       114.   0         \n2 Surface                     0.000206 0.0000442      4.65 0.00000337\n3 artistlivingLiving         -0.126    0.119         -1.06 0.289     \n4 Surface:artistlivingLiving  0.000479 0.000126       3.81 0.000139  \n```\n\n\n:::\n:::\n\n\n## Linear model with interaction effects {.smaller}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                        estimate std.error statistic    p.value\n  <chr>                          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)                 4.91     0.0432       114.   0         \n2 Surface                     0.000206 0.0000442      4.65 0.00000337\n3 artistlivingLiving         -0.126    0.119         -1.06 0.289     \n4 Surface:artistlivingLiving  0.000479 0.000126       3.81 0.000139  \n```\n\n\n:::\n:::\n\n\n$$\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface - 0.126 \\times artistliving$$ $$+ ~ 0.00048 \\times surface * artistliving$$\n\n## Interpretation of interaction effects {.smaller}\n\n::: incremental\n-   Rate of change in price as the surface area of the painting increases does vary between paintings by living and non-living artists (different slopes)\n-   Some paintings by living artists are more expensive than paintings by non-living artists, and some are not (different intercept).\n:::\n\n. . .\n\n::: columns\n::: {.column width=\"50%\"}\n::: incremental\n-   Non-living artist: $\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface$ $- 0.126 \\times 0 + 0.00048 \\times surface \\times 0$ $= 4.91 + 0.00021 \\times surface$\n-   Living artist: $\\widehat{log\\_price} = 4.91 + 0.00021 \\times surface$ $- 0.126 \\times 1 + 0.00048 \\times surface \\times 1$ $= 4.91 + 0.00021 \\times surface$ $- 0.126 + 0.00048 \\times surface$ $= 4.784 + 0.00069 \\times surface$\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr_files/figure-html/viz-interaction-effects2-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n# Comparing models {background-color=\"#92A86A\"}\n\n## R-squared\n\n-   $R^2$ is the percentage of variability in the response variable explained by the regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(pp_main_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01320884\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(pp_int_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0176922\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   Clearly the model with interactions has a higher $R^2$.\n\n. . .\n\n-   However using $R^2$ for model selection in models with multiple explanatory variables is not a good idea as $R^2$ increases when **any** variable is added to the model.\n\n## Adjusted R-squared\n\nIt appears that adding the interaction actually increased adjusted $R^2$, so we should indeed use the model with the interactions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(pp_main_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01258977\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(pp_int_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01676753\n```\n\n\n:::\n:::\n\n\n## Third order interactions\n\n-   Can you? Yes\n-   Should you? Probably not if you want to interpret these interactions in context of the data.\n\n## In pursuit of Occam's razor {.smaller}\n\n::: incremental\n-   Occam's Razor states that among competing hypotheses that predict equally well, the one with the fewest assumptions should be selected.\n\n-   Model selection follows this principle.\n\n-   We only want to add another variable to the model if the addition of that variable brings something valuable in terms of predictive power to the model.\n\n-   In other words, we prefer the simplest best model, i.e. **parsimonious** model.\n:::\n\n## Backward selection\n\nFor this demo, we'll ignore interaction effects...and just model main effects to start:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_full <-  lin_mod |>\n  fit(log_price ~ Width_in + Height_in + Surface + artistliving, data=pp) \n\nglance(pp_full)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02570141\n```\n\n\n:::\n:::\n\n\n-   $R^2$ (full): 0.0257014\n\n. . .\n\n### Remove `artistliving`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_noartist <- lin_mod |>\n  fit(log_price ~ Width_in + Height_in + Surface, data=pp) \n\nglance(pp_noartist)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02579859\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   $R^2$ (full): 0.0257\n-   $R^2$ (no `artistliving`): 0.0258\n\n...Improved variance explained\n\n. . .\n\n### Remove `Surface`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_noartist_nosurface <- lin_mod |>\n  fit(log_price ~ Width_in + Height_in, data=pp) \n\nglance(pp_noartist_nosurface)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02231559\n```\n\n\n:::\n:::\n\n\n. . .\n\n-   $R^2$ (full): 0.0257\n-   $R^2$ (no `artistliving`): 0.0258\n-   $R^2$ (no `artistliving` or `Surface`): 0.0223\n\n. . .\n\n...no longer gaining improvement, so we stick with: `log_price ~ Width_in + Height_in + Surface`\n\n## Other approach:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# requires package installation: \n# install.packages(\"olsrr\")\nlibrary(olsrr)\n```\n:::\n\n\n. . .\n\n**Step 1: Fit model (w/o `tidymodels`)**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit the model (not using tidymodels)\nmod <- lm(log_price ~ Width_in + Height_in + Surface + artistliving, data=pp_Surf_lt_5000)\n```\n:::\n\n\n. . .\n\n**Step 2: Determine which variables to remove**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_step_backward_p(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                             Elimination Summary                               \n------------------------------------------------------------------------------\n        Variable                      Adj.                                        \nStep      Removed       R-Square    R-Square     C(p)        AIC         RMSE     \n------------------------------------------------------------------------------\n   1    artistliving      0.0261      0.0251    3.8495    12603.7727    1.8315    \n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n...specifies that `artistliving` should be removed\n\n. . .\n\n**Step 2 (alternate): Compare all possible models...**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_step_all_possible(mod) |>\n  arrange(desc(adjr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Index N                              Predictors     R-Square Adj. R-Square\n1     11 3              Width_in Height_in Surface 0.0260749939  0.0251349118\n2     15 4 Width_in Height_in Surface artistliving 0.0263412027  0.0250876993\n3      5 2                      Width_in Height_in 0.0256902566  0.0250634893\n4     12 3         Width_in Height_in artistliving 0.0259732581  0.0250330779\n5      6 2                        Width_in Surface 0.0249136264  0.0242863596\n6     13 3           Width_in Surface artistliving 0.0251787948  0.0242378477\n7      7 2                   Width_in artistliving 0.0212864021  0.0206568018\n8      1 1                                Width_in 0.0209415833  0.0206267736\n9      8 2                    Surface artistliving 0.0132088377  0.0125897717\n10     2 1                                 Surface 0.0125899681  0.0122803381\n11    14 3          Height_in Surface artistliving 0.0130836930  0.0121310711\n12     9 2                       Height_in Surface 0.0126782901  0.0120431523\n13    10 2                  Height_in artistliving 0.0062698155  0.0056305552\n14     3 1                               Height_in 0.0058797727  0.0055601199\n15     4 1                            artistliving 0.0005531617  0.0002397573\n   Mallow's Cp\n1     3.849487\n2     5.000000\n3     3.077206\n4     4.174132\n5     5.555476\n6     6.709309\n7    17.130153\n8    16.230489\n9    51.971190\n10   52.001268\n11   45.305459\n12   44.599123\n13   65.048926\n14   64.293574\n15   91.485605\n```\n\n\n:::\n:::\n\n\n# End of Material Covered on Midterm\n\n## Recap {.smaller background-color=\"#92A86A\"}\n\n-   Can you model and interpret linear models with multiple predictors?\n-   Can you explain the difference in a model with main effects vs. interaction effects?\n-   Can you compare different models and determine how to proceed?\n-   Can you carry out and explain backward selection?\n",
    "supporting": [
      "09-mlr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}